spring.application.name=kafaka-demo
# ??
logging.level.root=info

# ???? Kafka ???? DEBUG???????????????
logging.level.org.apache.kafka=info
logging.level.org.apache.kafka.clients=info
logging.level.org.apache.kafka.clients.consumer=info
logging.level.org.apache.kafka.clients.consumer.internals.Fetcher=info
logging.level.org.apache.kafka.clients.FetchSessionHandler=info

#????Spring for Apache Kafka ????? info
logging.level.org.springframework.kafka=info

